### ISSUE TITLE
User can end the game and see a final score

### ISSUE THREAD

**Issue by MFS4711** [MFS4711/Hackathon-1-Quiz-Game#11]
In order to **end the game and see my final score** as a **user**, I can **end the game manually and get a message of my final score**

## Acceptance Criteria

- The user can click an "End Game" button to end the game manually.
- The final score is displayed after ending the game.
- The user can see a message like “Game Over” along with the total score.

## Tasks

- [ ] Add an "End Game" button to the UI.
- [ ] Implement game termination logic that shows the final score when clicked.
- [ ] Design a final screen with the total score and a "Play Again" option.
