### ISSUE TITLE
User can restart game after completing it

### ISSUE THREAD

**Issue by MFS4711** [MFS4711/Hackathon-1-Quiz-Game#2]
As a user, I want to have the option to play again right after finishing a game without having to navigate back to the main menu.

## Acceptance Criteria
* User can click a button at the end of the game to restart quiz
* the button should re-start quiz and not navigate to main menu 

## Tasks
- [ ] create re-start quiz button
- [ ] create function that restarts the quiz
- [ ] the user is returned to the correct page
