### ISSUE TITLE
User can see leaderboards to compare scores with others

### ISSUE THREAD

**Issue by MFS4711** [MFS4711/Hackathon-1-Quiz-Game#3]
As a user, I want to see a leaderboard that shows the highest scores so I can compete with others

## Acceptance Criteria
* create a table that logs users and their scores
* table displays scores in order from best to worst 

## Tasks
- [ ] create a leaderboard for the user
- [ ] create a function that logs a users score and compares it to the other scores
- [ ] create a function that ranks scores from highest to lowest
