### ISSUE TITLE
User can see a streak counter for consecutive correct answers

### ISSUE THREAD

**Issue by MFS4711** [MFS4711/Hackathon-1-Quiz-Game#5]
As a user, I want to know how many correct answers I’ve gotten in a row to challenge myself to keep the streak going.

## Acceptance Criteria
* The game displays a counter which adds one for each correct answer
* The streak counter resets to zero when with an incorrect answer

## Tasks
- [ ] Create visual display for the counter
- [ ] create a function that adds 1 when correct answer submitted
- [ ] counter resets to zero when incorrect answer is submitted
