### ISSUE TITLE
Game displays categories for questions eg(science, history, maths, pop culture)

### ISSUE THREAD

**Issue by MFS4711** [MFS4711/Hackathon-1-Quiz-Game#6]
As a user i want to be able to choose a category so i can play based on my interests or knowledge

## Acceptance Criteria
*  the game provides the user with a selection of categories to choose from

## Tasks
- [ ] implement a function to fetch categories for the database
- [ ] display categories to the user
- [ ] Ensure clear visibility for UX
