### ISSUE TITLE
User can see how many questions left

### ISSUE THREAD

**Issue by MFS4711** [MFS4711/Hackathon-1-Quiz-Game#7]
As a user, I want to know how many questions are remaining so I can pace myself.

## Acceptance Criteria
* The game displays the remaining amount of questions
* the remaining question total reduces after each question
* The visualisation is clear for the user

## Tasks
- [ ] Create a function that sets the number of questions
- [ ] the number of questions left to answer reduces by 1 after each question
- [ ] after the last question, the user receives score
